apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ocr-project
  namespace: argocd
spec:
  description: OCR Cluster Project
  sourceRepos:
    - https://github.com/Azmeth23/ocr-cluster-system
  destinations:
    - namespace: ocr-app
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocr-applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: api-gateway
        path: helm/api-gateway

      - name: ocr-model
        path: helm/ocr-model-server
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: ocr-project
      source:
        repoURL: https://github.com/Azmeth23/ocr-cluster-system.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: ocr-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true